version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sava
      POSTGRES_USER: sava_user
      POSTGRES_PASSWORD: sava_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sava_user -d sava"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: 